In [1]:
!pip install faker

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting faker
  Downloading Faker-18.9.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 25.4 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-18.9.0

In [11]:
import pandas as pd
import random
from faker import Faker

fake = Faker()

def generate_dummy_dataset(num_records, columns):
    data = []
    
    for _ in range(num_records):
        user_id = fake.uuid4()
        video_id = fake.uuid4()
        timestamp = fake.date_time_between(start_date='-1y', end_date='now')
        likes = random.randint(0, 1000)
        comments = random.randint(0, 200)
        age = random.randint(13, 65)
        gender = random.choice(['Male', 'Female'])
        location = fake.country()
        topic = fake.word()
        music = fake.random_element(['Pop', 'Rock', 'Hip Hop', 'Jazz', 'Classical'])
        visual_style = fake.random_element(['Bright', 'Dark', 'Colorful', 'Minimalistic'])
        videos_watched = random.randint(0, 100)
        videos_liked = random.randint(0, 50)
        videos_commented_on = random.randint(0, 20)
        
        row = [user_id, video_id, timestamp, likes, comments, age, gender, location, topic,
               music, visual_style, videos_watched, videos_liked, videos_commented_on]
        
        data.append(row)
    
    df = pd.DataFrame(data, columns=columns)
    return df

# Define the columns
columns = ['User ID', 'Video ID', 'Timestamp', 'Likes', 'Comments', 'Age', 'Gender',
           'Location', 'Topic', 'Music', 'Visual Style', 'Videos Watched',
           'Videos Liked', 'Videos Commented On']

# Generate a dummy dataset with 2000000 records
dummy_dataset = generate_dummy_dataset(2000000, columns)

# Save the dataset to a CSV file
dummy_dataset.to_csv('dummy_dataset.csv', index=False)

In [12]:
df1 = pd.read_csv('dummy_dataset.csv')
df1

,User ID,Video ID,Timestamp,Likes,Comments,Age,Gender,Location,Topic,Music,Visual Style,Videos Watched,Videos Liked,Videos Commented On
0,83034053-5a9e-4e8f-878e-891cc289b565,84aff707-db50-446c-9d29-676874be5333,2023-04-24 15:14:30,576,59,18,Male,Greenland,listen,Pop,Bright,10,45,15
1,cd87ebfc-bc99-40a6-a62f-6aab3d9a0a5b,04626321-7468-4a63-943a-1cc316cb8bb0,2022-07-04 16:54:06,60,157,28,Male,Timor-Leste,plan,Jazz,Minimalistic,47,36,0
2,75c6075c-ca6b-4cc0-b2ea-682b02aacf99,cbf3d19c-a9db-43b0-9279-919678bd3dd7,2022-09-01 08:54:22,567,167,54,Male,Suriname,statement,Hip Hop,Dark,33,23,16
3,472951ff-7153-40c3-8d2b-f51082060491,bd2763b7-52b6-40a3-ba65-9920c6dcd839,2022-10-14 08:23:13,501,101,22,Female,Comoros,firm,Hip Hop,Bright,89,12,6
4,c29d96ea-dc7d-4c17-81d9-53546a418e80,bef581a1-4538-43c8-aa40-c37fa9d18d7f,2022-07-22 15:15:38,11,30,57,Female,Portugal,can,Jazz,Bright,17,9,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999995,58362455-184a-4b6d-9705-afb5d4350a57,1c491055-1a2b-4dcd-99b9-1202569df700,2022-07-02 07:02:48,56,186,22,Female,Switzerland,city,Classical,Bright,18,10,18
1999996,f72ce168-7332-483b-9d83-79011dbc4046,8bc3b99c-2e13-4ad6-ba28-d74caac6fab8,2023-04-10 02:51:55,16,102,24,Female,Christmas Island,two,Pop,Bright,67,40,13
1999997,febe2643-b476-4ac6-9b08-22c3d4aee355,54e8018f-6757-4066-9213-6883c3dd49f4,2022-08-16 20:08:23,610,134,17,Male,Burundi,itself,Pop,Minimalistic,90,27,0
1999998,87244bd5-34f9-4172-bfec-d905d9a4a602,bbfdba64-7c50-4503-a0a8-f4d05887c801,2022-05-27 13:10:21,514,27,30,Male,Chad,goal,Classical,Colorful,18,29,0
1999999,8e6e35ba-e9f2-4e19-8ce8-410a98c738ca,5b5d2874-33b5-459d-aa60-3c783e4e993d,2022-10-01 16:01:32,659,161,65,Male,Turks and Caicos Islands,country,Jazz,Bright,10,35,10

In [13]:
df1.shape

(2000000, 14)

This dataset includes the following information for each video:

**User ID**: The ID of the user who posted the video.

**Video ID**: The ID of the video.

**Timestamp**: The date and time the video was posted.

**Likes**: The number of likes the video has received.

**Comments**: The number of comments the video has received.

**Age**: The age of the user.

**Gender**: The gender of the user.

**Location**: The location of the user.

**Topic**: The topic of the video.

**Music**: The music in the video.

**Visual style**: The visual style of the video.

**Videos watched**: The videos that the user has watched.

**Videos liked**: The videos that the user has liked.

**Videos commented on**: The videos that the user has commented on.

This dataset can be used to build a recommendation algorithm that recommends videos to users based on their past behavior, demographics, and interests.

In [32]:
df1[df1['Location'] == 'Ghana']

,User ID,Video ID,Timestamp,Likes,Comments,Age,Gender,Location,Topic,Music,Visual Style,Videos Watched,Videos Liked,Videos Commented On
164,750a1db4-eb83-40cd-a231-bcdc144b35a3,40c0d98f-6026-46df-823b-78c0db702e98,2022-07-23 13:54:57,129,85,35,Male,Ghana,treat,Jazz,Bright,77,0,0
257,eeef9ec8-4512-44a5-9d5d-95c88f07bd7d,3147d8f4-ad73-4079-a37b-00f0dd8b8618,2022-08-18 02:34:08,265,97,59,Female,Ghana,miss,Rock,Minimalistic,21,9,7
394,2325c738-3d46-4971-8dee-238d5a587e3a,b0912734-d51f-4f63-9f1a-826fc25cc6c8,2022-08-18 08:05:26,247,63,41,Female,Ghana,perhaps,Classical,Minimalistic,4,30,0
441,a77df012-45c4-4e0e-a6fc-73ede5a9ab3f,06f8f9ee-5529-41c3-a2f6-3b29e30bf187,2022-11-20 11:04:08,462,25,29,Male,Ghana,yet,Jazz,Bright,39,41,2
573,ff451961-a182-4caf-a779-c23ef963133d,297ff7ab-60c0-44c3-a6b9-fd243a9e6b44,2022-10-07 22:26:52,962,156,47,Male,Ghana,career,Classical,Colorful,76,20,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997602,c553c17e-71f7-4177-a03b-f91c281f578f,66af4e2d-49da-4631-afb0-d2990fdcff06,2023-04-05 08:25:08,481,61,26,Male,Ghana,their,Classical,Colorful,77,31,19
1997987,569f9f7c-b866-408b-a246-b63b46d4affe,d7d11d2e-f3be-409f-829a-a9bfad992290,2022-09-01 23:55:15,793,0,20,Female,Ghana,term,Hip Hop,Colorful,17,47,6
1998584,30032585-72d5-48ca-9380-ee19f49e5724,d20da1d8-050c-4037-b366-76d357952dd1,2022-09-25 08:16:53,256,39,40,Male,Ghana,method,Classical,Colorful,74,41,8
1999555,3d81cbde-a1e5-467d-bc13-2af31b6d1482,6b5a7f82-50f5-4b7f-9c91-6e8b1ed41d66,2022-12-01 09:19:38,822,176,32,Female,Ghana,letter,Pop,Bright,69,33,19
1999579,f1c25dbb-d063-497e-be6d-111c87c5dcc0,d6db0574-c332-4fe1-a040-947d791660b8,2023-03-23 02:16:47,938,94,16,Male,Ghana,method,Classical,Dark,54,39,1